name: Calculator-tests

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install pytest

      - name: Run addition test
        run: |
          result=$(python main.py 5 + 3)
          if [[ $result != *"8"* ]]; then
            echo "Addition test failed: Expected '8', got '$result'"
            exit 1
          fi

      - name: Run subtraction test
        run: |
          result=$(python main.py 7 - 4)
          if [[ $result != *"3"* ]]; then
            echo "Subtraction test failed: Expected '3', got '$result'"
            exit 1
          fi
