name: Cripto-test

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8' # Укажите версию Python, которую вы используете

      - name: Install dependencies
        run: |
          pip install pyqt5

      - name: Run main.py and test
        run: |
          python main.py &
          sleep 5
          if ! pgrep -f main.py > /dev/null; then
            echo "First test failed: Application did not start"
            exit 1
          fi

          # Addition test
          echo "1+2=" | python main.py | grep -q "3"
          if [ $? -ne 0 ]; then
            echo "Addition test failed: 1 + 2 did not equal 3"
            exit 1
          fi

          # Subtraction test
          echo "5-3=" | python main.py | grep -q "2"
          if [ $? -ne 0 ]; then
            echo "Subtraction test failed: 5 - 3 did not equal 2"
            exit 1
          fi

          kill $(pgrep -f main.py)
          echo "All tests passed: Addition and subtraction tests completed successfully"
